# Official repository: https://github.com/Steeven-Duncan-First/upptime

owner: Steeven-Duncan-First
repo: upptime

sites:
  - name: Odoo Fresh Fish Production
    url: https://odoo.freshfishcameroun.com
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 301
      - 302

  - name: Odoo Fresh Fish API
    url: https://odoo.freshfishcameroun.com/web/database/selector
    maxResponseTime: 3000

status-website:
  logoUrl: https://freshfishcameroun.com/logo.png
  name: Fresh Fish Cameroon Status
  introTitle: "Statut des Services ODOO de FRESH FISH CAMEROUN"
  introMessage: Surveillance en temps réel de nos infrastructures
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Configuration des vérifications
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Notifications
notifications:
  - type: custom
    name: Make Webhook
    check: "all"
    body: |
      {
        "site": "$SITE_NAME",
        "url": "$SITE_URL",
        "status": "$SITE_STATUS",
        "statusCode": "$RESPONSE_CODE",
        "responseTime": "$RESPONSE_TIME",
        "timestamp": "$TIMESTAMP",
        "message": "$SITE_STATUS_MESSAGE"
      }
    headers:
      Content-Type: application/json
    method: POST
    url: https://hook.eu1.make.com/injscwc69oe6ktqcgl5o2p1g66m5t04t

# Assignees pour les issues GitHub
assignees:
  - Steeven-Duncan-First

user-agent: upptime-freshfish

# Langue française
i18n:
  footer: Upptime Fresh Fish Cameroun - Propulsé par [Upptime](https://upptime.js.org)
  liveStatus: Statut en direct
  overallUptime: Disponibilité globale
  overallUptimeTitle: Disponibilité globale
  averageResponseTime: Temps de réponse moyen
  averageResponseTimeTitle: Temps de réponse moyen
  sevelDayResponseTime: Temps de réponse (7j)
  responseTimeMs: Temps de réponse (ms)
  up: Opérationnel
  down: Hors service
  degraded: Dégradé
  ms: ms
  loading: Chargement
  navGitHub: GitHub
  rateLimitExceededTitle: Limite de débit dépassée
  rateLimitExceededIntro: Trop de requêtes
  rateLimitExceededWhatDoesThisMean: Que signifie cela ?
  rateLimitExceededErrorHelpText: Attendez quelques minutes et réessayez
  errorTitle: Une erreur s'est produite
  errorIntro: Une erreur s'est produite lors de la récupération des données
  errorText: Veuillez réessayer plus tard
  errorHome: Retour à l'accueil
  pastIncidents: Incidents passés
  activeIncidents: Incidents actifs
  incidentDetails: Détails de l'incident
  incidentFixed: Résolu
  incidentOngoing: En cours
  incidentOpenedAt: Ouvert le
  incidentClosedAt: Fermé le
  incidentViewOnGitHub: Voir sur GitHub
  incidentCommentSummary: Publié le $DATE par $AUTHOR
  incidentBack: ← Retour à tous les incidents
  pastIncidentsResolved: Résolu en $MINUTES minutes avec $POSTS publications
  liveStatusHtmlComment: "<!-- Statut en direct -->"
